[official]
bootc_runtime = [
  "ostree",
  "dracut",
  "base-devel",
  "git",
]

bootc_build = [
  "rust",
  "go-md2man",
]

kernel_runtime = [
  "linux",
  "linux-firmware",
  "intel-ucode",
  "cpio",
]

system = [
  "btrfs-progs",
  "e2fsprogs",
  "xfsprogs",
  "dosfstools",
  "fuse-overlayfs",
  "fuse2",
  "skopeo",
  "dbus",
  "dbus-glib",
  "glib2",
  "shadow",
  "networkmanager",
  "network-manager-applet",
  "openbsd-netcat",
  "pipewire",
  "pipewire-alsa",
  "pipewire-pulse",
  "pipewire-jack",
  "pavucontrol",
  "wireplumber",
  "openssh",
  "man",
  "nano",
  "vim",
  "unzip",
  "go-yq",
  "wget",
  "podman",
  "just",
  "git",
  "hyprland",
  "hyprpaper",
  "hyprpicker",
  "hypridle",
  "hyprlock",
  "hyprpolkitagent",
  "swaync",
  "grim",
  "slurp",
  "kitty",
  "qt5-wayland",
  "qt6-wayland",
  "waybar",
  "otf-font-awesome",
  "nautilus",
  "gnome-keyring",
  "seahorse",
  "uwsm",
  "libnewt",
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-gtk",
  "brightnessctl",
  "playerctl",
  "usbutils",
  "innoextract",
  "python-cryptography",
  "python-pyusb",
  "firefox",
  "mesa",
  "intel-media-driver",
  "intel-media-sdk",
  "vulkan-intel",
  "intel-gpu-tools",
  "libva-utils",
  "vdpauinfo",
  "vulkan-tools",
  "chrony",
  "throttled",
  "fwupd",
  "tlp",
  "flatpak",
  "flatpak-builder",
  "bluez",
  "bluez-utils",
  "blueman",
  "ttf-jetbrains-mono-nerd",
  "code",
  "jq",
  "mise",
  "rustup",
  "go",
  "gobject-introspection",
  "github-cli",
  "libqalculate",
  "fd",
  "imagemagick",
  "wl-clipboard",
  "libnotify",
  "ffmpeg4.4",
  "chromium",
]

[aur]
packages = [
  "1password",
  "1password-cli",
  "open-fprintd",
  "python-validity",
  "jetbrains-toolbox",
  "cloudflare-warp-bin",
  "walker",
  "hyprshot-git",
  "elephant",
  "elephant-desktopapplications",
  "elephant-calc",
  "elephant-runner",
  "elephant-files",
  "elephant-websearch",
  "elephant-clipboard",
  "parsec-bin",
  "sublime-text-4",
  "t3code-bin",
]

[versions]
bootc = "v1.12.1"

[keys.onepassword]
url = "https://downloads.1password.com/linux/keys/1password.asc"
fingerprint = "3FEF9748469ADBE15DA7CA80AC2D62742012EA22"
