general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint:enabled = true
    fingerprint:ready_message = Scan finger or type password
    fingerprint:present_message = Reading fingerprint...
    fingerprint:retry_delay = 250
}

background {
    monitor =
    path = /usr/share/backgrounds/arch-bootc/wallpaper.png
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = $TIME
    color = rgba(230,230,230,1.0)
    font_size = 36
    font_family = JetBrainsMonoNerdFont
    position = 0, 28
    halign = center
    valign = center
}

shape {
    monitor =
    size = 360, 40
    color = rgba(0,0,0,0.25)
    rounding = 5
    border_size = 1
    border_color = rgba(255,255,255,0.08)
    position = 0, -60
    halign = center
    valign = center
}

shape {
    monitor =
    size = 48, 40
    color = rgba(255,255,255,0.04)
    rounding = 5
    position = 156, -60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 292, 40
    outline_thickness = 0
    dots_size = 0.18
    dots_spacing = 0.20
    dots_center = true
    fade_on_empty = false
    outer_color = rgba(0,0,0,0.0)
    inner_color = rgba(0,0,0,0.0)
    font_color = rgba(230,230,230,0.96)
    font_family = JetBrainsMonoNerdFont
    font_size = 3
    placeholder_text = Password
    rounding = 5
    check_color = rgba(0,0,0,0.0)
    fail_color = rgba(0,0,0,0.0)
    fail_text =
    position = -24, -60
    halign = center
    valign = center
}

shape {
    monitor =
    size = 1, 40
    color = rgba(255,255,255,0.08)
    rounding = 1
    position = 132, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:250] sh -c 'case "$FPRINTPROMPT$FPRINTFAIL" in *[![:space:]]*) printf "" ;; *) printf "󰈷 " ;; esac'
    color = rgba(230,230,230,0.45)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Mono
    position = 155, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:250] sh -c 'case "$FPRINTFAIL" in *[![:space:]]*) printf "󰈷 " ;; *) printf "" ;; esac'
    color = rgba(245,60,60,0.95)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Mono
    position = 155, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:250] sh -c 'case "$FPRINTPROMPT" in *[![:space:]]*) printf "󰈷 " ;; *) printf "" ;; esac'
    color = rgba(255,255,255,0.98)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Mono
    position = 155, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = $PAMFAIL
    color = rgba(245,60,60,0.8)
    font_size = 11
    font_family = JetBrainsMonoNerdFont
    position = 0, -26
    halign = center
    valign = center
}
