[aur]
packages = [
  "1password",
  "1password-cli",
  "open-fprintd",
  "python-validity",
  "jetbrains-toolbox",
  "cloudflare-warp-bin",
  "walker",
  "hyprshot-git",
  "elephant",
  "elephant-desktopapplications",
  "elephant-calc",
  "elephant-runner",
  "elephant-files",
  "elephant-websearch",
  "elephant-clipboard",
  "parsec-bin",
  "sublime-text-4",
  "t3code-bin",
]
